# Generated by Django 4.2 on 2023-04-07 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0002_setupintent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setupintent',
            name='from_customer',
        ),
        migrations.RemoveField(
            model_name='setupintent',
            name='to_customer',
        ),
        migrations.AddField(
            model_name='setupintent',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to='stripe_payment.customer', verbose_name='From Customer'),
        ),
    ]
