# Generated by Django 4.2 on 2023-04-12 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payment', '0003_remove_setupintent_from_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('describtion', models.TextField(verbose_name='Describtion')),
                ('amount', models.PositiveBigIntegerField(verbose_name='Amount ')),
                ('currency', models.CharField(default='pln', max_length=20, verbose_name='Currency')),
                ('payment_method_types', models.CharField(max_length=500)),
                ('capture_method', models.CharField(default='manual', max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_payment.customer', verbose_name='Customer')),
            ],
        ),
    ]
