# Generated by Django 4.2 on 2023-04-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Done', 'Done'), ('Failed', 'Failed')], default='Pending', max_length=31)),
                ('payment_id', models.CharField(max_length=127, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
