# Generated by Django 4.2 on 2023-04-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_payment_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='client_secret',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
