# Generated by Django 4.2 on 2023-04-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_client_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='client_secret',
        ),
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='usd', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(default='-', max_length=127),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Created', 'Created'), ('Done', 'Done'), ('Failed', 'Failed')], default='Requested', max_length=31),
        ),
    ]
