# Generated by Django 4.2 on 2023-04-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('payment_status', models.CharField(max_length=32)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_currency', models.CharField(max_length=3)),
                ('payer_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='LineItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
