# Generated by Django 4.2 on 2023-04-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_module', '0004_cart_delete_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
