# Generated by Django 4.2 on 2023-04-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay_module', '0005_cart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
