# Generated by Django 4.2 on 2023-04-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay_module', '0006_product_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
    ]
