# Generated by Django 4.2 on 2023-04-15 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay_module', '0007_remove_product_product_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='LineItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
